---
title: "Vince's LeetCode solutions with test cases."
output: html_document
---




```

LeetCode 88. Merge Sorted Array
```{python}
class Solution:
    def merge(self, nums1: List[int], m: int, nums2: List[int], n: int) -> None:
        """
        Do not return anything, modify nums1 in-place instead.
        """
                
```

LeetCode 118. Pascal's Triangle.
```{python}
from math import comb
from typing import List

class Solution:
    def generate(self, numRows: int) -> List[List[int]]:
        allRows = []
        for i in range(numRows):
            rowI = []
            
            for j in range(i + 1):
                rowI.append(comb(i, j))
            
            allRows.append(rowI)
    
        return allRows

```

Test cases:
```{python}
print(Solution().generate(numRows = 1))
print(Solution().generate(numRows = 2))
print(Solution().generate(numRows = 3))
print(Solution().generate(numRows = 4))
print(Solution().generate(numRows = 5))


```


LeetCode 119. Pascal's Triangle 2.
```{python}
from math import comb

class Solution:
    def getRow(self, rowIndex: int) -> List[int]:
        thisRow = []
        
        for j in range(rowIndex + 1):
                thisRow.append(comb(rowIndex, j))
    
        return thisRow

# Test cases

print(Solution().getRow(rowIndex = 0))
print(Solution().getRow(rowIndex = 1))
print(Solution().getRow(rowIndex = 2))
print(Solution().getRow(rowIndex = 3))
print(Solution().getRow(rowIndex = 4))

```


LeetCode 121. Best Time to Buy and Sell Stock
```{python}
class Solution:
    def maxProfit(self, prices: List[int]) -> int:
        maxProfit = 0
        left = 0
        right = 1
             
        while right < len(prices):
            if prices[left] < prices[right]:
                currentProfit = prices[right] - prices[left]
                maxProfit = max(maxProfit, currentProfit)
            else:
                left = right
            right += 1
                
        return maxProfit

# Test Cases

print(Solution().maxProfit(prices = [7,1,5,3,6,4]))
print(Solution().maxProfit(prices = [7,6,4,3,1]))

```

LeetCode 122. Best Time to Buy and Sell Stock II
```{python}

```

LeetCode 123. Best Time to Buy and Sell Stock III
```{python}

```

LeetCode125: Valid Palindrome
```{python}
class Solution:
    def isPalindrome(self, s: str) -> bool:

        # Remove punctuation and force lowercase
        s = re.sub(r'[^a-zA-Z0-9]', '', s).lower()

        return s == s[::-1]

print(Solution().isPalindrome(s = "abba"))
print(Solution().isPalindrome(s = "abcd"))
print(Solution().isPalindrome(s = "abcdedcba"))
print(Solution().isPalindrome(s = "A man, a plan, a canal: Panama"))
print(Solution().isPalindrome(s = "race a car"))
print(Solution().isPalindrome(s = " "))
print(Solution().isPalindrome(s = "0P"))
```

LeetCode 556. Reshape the Matrix.
```{python}
class Solution:
  def matrixReshape(self, mat: List[List[int]], r: int, c: int) -> List[List[int]]:



```
